<?php

namespace Database\Seeders;

use App\Models\RekapHotel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RekapHotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $rekap = [
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 106,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 2821,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 450,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 151,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 536,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 17,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 262,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 774,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 56,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 16,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 85,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 2200,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 89,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 90,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 612,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 20,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 194,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 848,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 56,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 23,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 111,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 2892,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 117,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 102,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 628,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 13,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 210,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 860,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 56,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 33,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 106,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 2188,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 77,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 122,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 698,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 34,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 145,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 609,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 31,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 26,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 132,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 3751,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 74,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 146,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 1015,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 47,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 190,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 951,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 57,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 27,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 107,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 2694,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 81,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 139,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 780,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 31,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 170,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 783,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 51,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 24,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 115,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 3460,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 76,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 126,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 882,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 54,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 175,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 788,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 43,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 43,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 111,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 3182,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 85,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 112,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 831,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 51,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 245,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 856,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 48,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 54,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 121,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 3321,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 65,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 98,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 773,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 34,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 204,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 875,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 77,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 54,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 118,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 3636,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 126,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 105,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 694,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 57,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 108,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 1133,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 68,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 119,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 3226,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 103,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 57,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 1,
                'pengunjung_nusantara' => 111,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 2,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 3,
                'pengunjung_nusantara' => 118,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 4,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 5,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 6,
                'pengunjung_nusantara' => 67,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 7,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 8,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 9,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 10,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 11,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 12,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 13,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 14,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 15,
                'pengunjung_nusantara' => 0,
                'pengunjung_mancanegara' => 0,
                'kamar_terjual' => 0,
            ],
        ];

        foreach ($rekap as $data) {
            RekapHotel::create($data);
        }
    }
}
