<?php

namespace Database\Seeders;

use App\Models\Rekap;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RekapSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $rekap = [
            [
                'tanggal' => '2023-01-01',
                'id_wisata' => 1,
                'wisatawan_domestik' => 100,
                'wisatawan_mancanegara' => 50,
                'total_pendapatan' => 1000000,
            ],
            [
                'tanggal' => '2023-01-02',
                'id_wisata' => 1,
                'wisatawan_domestik' => 100,
                'wisatawan_mancanegara' => 50,
                'total_pendapatan' => 1000000,
            ],
            [
                'tanggal' => '2023-01-03',
                'id_wisata' => 1,
                'wisatawan_domestik' => 100,
                'wisatawan_mancanegara' => 50,
                'total_pendapatan' => 1000000,
            ],
            [
                'tanggal' => '2023-01-04',
                'id_wisata' => 1,
                'wisatawan_domestik' => 100,
                'wisatawan_mancanegara' => 50,
                'total_pendapatan' => 1000000,
            ],
            [
                'tanggal' => '2023-01-05',
                'id_wisata' => 1,
                'wisatawan_domestik' => 100,
                'wisatawan_mancanegara' => 50,
                'total_pendapatan' => 1000000,
            ],
            [
                'tanggal' => '2023-01-06',
                'id_wisata' => 1,
                'wisatawan_domestik' => 100,
                'wisatawan_mancanegara' => 50,
                'total_pendapatan' => 1000000,
            ],
            [
                'tanggal' => '2023-01-07',
                'id_wisata' => 1,
                'wisatawan_domestik' => 100,
                'wisatawan_mancanegara' => 50,
                'total_pendapatan' => 1000000,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 1,
                'wisatawan_domestik' => 8127,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 2,
                'wisatawan_domestik' => 1314,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 4,
                'wisatawan_domestik' => 86,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 5,
                'wisatawan_domestik' => 116,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 6,
                'wisatawan_domestik' => 368,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 7,
                'wisatawan_domestik' => 156,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 8,
                'wisatawan_domestik' => 1520,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 9,
                'wisatawan_domestik' => 602,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 18,
                'wisatawan_domestik' => 1511,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 19,
                'wisatawan_domestik' => 29,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 20,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 21,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 29,
                'wisatawan_domestik' => 2978,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 30,
                'wisatawan_domestik' => 1259,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 35,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 1,
                'wisatawan_domestik' => 6115,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 2,
                'wisatawan_domestik' => 3596,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 4,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 5,
                'wisatawan_domestik' => 333,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 6,
                'wisatawan_domestik' => 713,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 7,
                'wisatawan_domestik' => 349,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 8,
                'wisatawan_domestik' => 1520,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 9,
                'wisatawan_domestik' => 1001,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 12,
                'wisatawan_domestik' => 117,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 18,
                'wisatawan_domestik' => 839,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 19,
                'wisatawan_domestik' => 52,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 20,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 21,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 29,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 30,
                'wisatawan_domestik' => 724,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 35,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 1,
                'wisatawan_domestik' => 1259,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 2,
                'wisatawan_domestik' => 1298,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 4,
                'wisatawan_domestik' => 305,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 5,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 6,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 7,
                'wisatawan_domestik' => 130,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 8,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 9,
                'wisatawan_domestik' => 708,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 12,
                'wisatawan_domestik' => 2,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 18,
                'wisatawan_domestik' => 427,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 19,
                'wisatawan_domestik' => 45,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 20,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 21,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 29,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 30,
                'wisatawan_domestik' => 467,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 35,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 1,
                'wisatawan_domestik' => 2776,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 13900000,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 2,
                'wisatawan_domestik' => 913,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 4500000,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 4,
                'wisatawan_domestik' => 104,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 520000,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 5,
                'wisatawan_domestik' => 67,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 300000,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 6,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 7,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 8,
                'wisatawan_domestik' => 141,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 700000,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 9,
                'wisatawan_domestik' => 358,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 1800000,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 10,
                'wisatawan_domestik' => 680,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 3400000,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 13,
                'wisatawan_domestik' => 15,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 75000,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 18,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 19,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 20,
                'wisatawan_domestik' => 1012,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 5000000,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 21,
                'wisatawan_domestik' => 27,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 135000,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 29,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 30,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 1,
                'wisatawan_domestik' => 1613,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 8000000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 2,
                'wisatawan_domestik' => 1070,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 5350000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 4,
                'wisatawan_domestik' => 105,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 525000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 5,
                'wisatawan_domestik' => 67,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 550000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 6,
                'wisatawan_domestik' => 73,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 365000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 7,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 8,
                'wisatawan_domestik' => 93,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 465000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 9,
                'wisatawan_domestik' => 243,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 1215000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 10,
                'wisatawan_domestik' => 710,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 3550000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 13,
                'wisatawan_domestik' => 26,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 130000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 18,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 19,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 20,
                'wisatawan_domestik' => 317,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 1585000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 21,
                'wisatawan_domestik' => 117,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 585000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 29,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 30,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 31,
                'wisatawan_domestik' => 1674,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 8370000,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 1,
                'wisatawan_domestik' => 1036,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 5180000,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 2,
                'wisatawan_domestik' => 1036,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 5180000,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 4,
                'wisatawan_domestik' => 96,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 480000,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 5,
                'wisatawan_domestik' => 97,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 485000,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 6,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 7,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 8,
                'wisatawan_domestik' => 42,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 210000,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 9,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 10,
                'wisatawan_domestik' => 760,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 3800000,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 13,
                'wisatawan_domestik' => 11,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 55000,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 18,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 19,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 20,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 21,
                'wisatawan_domestik' => 14,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 70000,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 29,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 30,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
        ];

        foreach ($rekap as $data) {
            Rekap::create($data);
        }
    }
}
