<?php

namespace Database\Seeders;

use App\Models\Rekap;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RekapSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $rekap = [
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 1,
                'wisatawan_domestik' => 8127,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 2,
                'wisatawan_domestik' => 1314,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 4,
                'wisatawan_domestik' => 86,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 5,
                'wisatawan_domestik' => 116,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 6,
                'wisatawan_domestik' => 368,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 7,
                'wisatawan_domestik' => 156,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 8,
                'wisatawan_domestik' => 1520,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 9,
                'wisatawan_domestik' => 602,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 18,
                'wisatawan_domestik' => 1511,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 19,
                'wisatawan_domestik' => 29,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 20,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 21,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 29,
                'wisatawan_domestik' => 2978,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 30,
                'wisatawan_domestik' => 1259,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-17',
                'id_wisata' => 35,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 1,
                'wisatawan_domestik' => 6115,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 2,
                'wisatawan_domestik' => 3596,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 4,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 5,
                'wisatawan_domestik' => 333,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 6,
                'wisatawan_domestik' => 713,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 7,
                'wisatawan_domestik' => 349,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 8,
                'wisatawan_domestik' => 1520,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 9,
                'wisatawan_domestik' => 1001,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 12,
                'wisatawan_domestik' => 117,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 18,
                'wisatawan_domestik' => 839,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 19,
                'wisatawan_domestik' => 52,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 20,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 21,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 29,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 30,
                'wisatawan_domestik' => 724,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-18',
                'id_wisata' => 35,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 1,
                'wisatawan_domestik' => 1259,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 2,
                'wisatawan_domestik' => 1298,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 4,
                'wisatawan_domestik' => 305,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 5,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 6,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 7,
                'wisatawan_domestik' => 130,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 8,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 9,
                'wisatawan_domestik' => 708,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 12,
                'wisatawan_domestik' => 2,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 18,
                'wisatawan_domestik' => 427,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 19,
                'wisatawan_domestik' => 45,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 20,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 21,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 29,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 30,
                'wisatawan_domestik' => 467,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-19',
                'id_wisata' => 35,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 1,
                'wisatawan_domestik' => 2776,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 2,
                'wisatawan_domestik' => 913,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 4,
                'wisatawan_domestik' => 104,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 5,
                'wisatawan_domestik' => 67,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 6,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 7,
                'wisatawan_domestik' => 141,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 8,
                'wisatawan_domestik' => 358,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 9,
                'wisatawan_domestik' => 680,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 12,
                'wisatawan_domestik' => 15,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 18,
                'wisatawan_domestik' => 1012,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 19,
                'wisatawan_domestik' => 27,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 20,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 21,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 29,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 30,
                'wisatawan_domestik' => 534,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-20',
                'id_wisata' => 35,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 1,
                'wisatawan_domestik' => 1613,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 2,
                'wisatawan_domestik' => 1070,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 4,
                'wisatawan_domestik' => 105,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 5,
                'wisatawan_domestik' => 110,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 6,
                'wisatawan_domestik' => 73,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 7,
                'wisatawan_domestik' => 93,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 8,
                'wisatawan_domestik' => 243,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 9,
                'wisatawan_domestik' => 710,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 12,
                'wisatawan_domestik' => 26,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 18,
                'wisatawan_domestik' => 317,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 19,
                'wisatawan_domestik' => 117,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 20,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 21,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 29,
                'wisatawan_domestik' => 1674,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 30,
                'wisatawan_domestik' => 325,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-21',
                'id_wisata' => 35,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 1,
                'wisatawan_domestik' => 1036,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 2,
                'wisatawan_domestik' => 1036,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 3,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 4,
                'wisatawan_domestik' => 96,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 5,
                'wisatawan_domestik' => 97,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 6,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 7,
                'wisatawan_domestik' => 42,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 8,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 9,
                'wisatawan_domestik' => 760,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 12,
                'wisatawan_domestik' => 11,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 18,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 19,
                'wisatawan_domestik' => 14,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 20,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 21,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 24,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 25,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 29,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 30,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 32,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
            ],
            [
                'tanggal' => '2022-12-22',
                'id_wisata' => 35,
                'wisatawan_domestik' => 0,
                'wisatawan_domestik' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 1,
                'wisatawan_domestik' => 25397,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 509940000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 2,
                'wisatawan_domestik' => 13233,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 187324000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 3,
                'wisatawan_domestik' => 3397,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 13981000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 4,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 5,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 6,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 7,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 8,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 60350000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 9,
                'wisatawan_domestik' => 10492,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 182420000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 12,
                'wisatawan_domestik' => 585,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 3950000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 13,
                'wisatawan_domestik' => 59,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 750000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 15,
                'wisatawan_domestik' => 2019,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 6190000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 16,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 17,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 18,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 5975000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 19,
                'wisatawan_domestik' => 933,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 7658000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 20,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 21,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 22,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 23,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 24,
                'wisatawan_domestik' => 1326,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 7280000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 25,
                'wisatawan_domestik' => 267,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 1809000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 26,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 27,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 28,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 29,
                'wisatawan_domestik' => 7485,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 149209000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 30,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 11275000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 31,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 32,
                'wisatawan_domestik' => 2107,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 8565000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 33,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 34,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_wisata' => 35,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 1,
                'wisatawan_domestik' => 106,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 25300000,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 2,
                'wisatawan_domestik' => 2821,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 3,
                'wisatawan_domestik' => 450,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 4,
                'wisatawan_domestik' => 151,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 5,
                'wisatawan_domestik' => 536,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 6,
                'wisatawan_domestik' => 17,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 7,
                'wisatawan_domestik' => 262,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 12725000,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 8,
                'wisatawan_domestik' => 774,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 562316250,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 9,
                'wisatawan_domestik' => 56,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 10,
                'wisatawan_domestik' => 16,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-01-31',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 1,
                'wisatawan_domestik' => 85,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 19745000,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 2,
                'wisatawan_domestik' => 2200,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 3,
                'wisatawan_domestik' => 89,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 4,
                'wisatawan_domestik' => 90,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 5,
                'wisatawan_domestik' => 612,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 6,
                'wisatawan_domestik' => 20,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 7,
                'wisatawan_domestik' => 194,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 9840000,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 8,
                'wisatawan_domestik' => 848,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 540189830,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 9,
                'wisatawan_domestik' => 56,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 10,
                'wisatawan_domestik' => 23,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-02-28',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 1,
                'wisatawan_domestik' => 111,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 24796000,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 2,
                'wisatawan_domestik' => 2892,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 3,
                'wisatawan_domestik' => 117,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 4,
                'wisatawan_domestik' => 102,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 5,
                'wisatawan_domestik' => 628,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 6,
                'wisatawan_domestik' => 13,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 7,
                'wisatawan_domestik' => 210,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 9900000,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 8,
                'wisatawan_domestik' => 860,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 571226847,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 9,
                'wisatawan_domestik' => 56,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 10,
                'wisatawan_domestik' => 33,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-03-31',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 1,
                'wisatawan_domestik' => 106,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 24640000,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 2,
                'wisatawan_domestik' => 2188,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 3,
                'wisatawan_domestik' => 77,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 4,
                'wisatawan_domestik' => 122,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 5,
                'wisatawan_domestik' => 698,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 6,
                'wisatawan_domestik' => 34,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 7,
                'wisatawan_domestik' => 145,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 6780000,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 8,
                'wisatawan_domestik' => 609,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 366297453,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 9,
                'wisatawan_domestik' => 31,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 10,
                'wisatawan_domestik' => 26,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-04-30',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 1,
                'wisatawan_domestik' => 132,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 29997000,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 2,
                'wisatawan_domestik' => 3751,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 3,
                'wisatawan_domestik' => 74,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 4,
                'wisatawan_domestik' => 146,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 5,
                'wisatawan_domestik' => 1015,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 6,
                'wisatawan_domestik' => 47,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 7,
                'wisatawan_domestik' => 190,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 9485000,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 8,
                'wisatawan_domestik' => 951,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 644687243,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 9,
                'wisatawan_domestik' => 57,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 10,
                'wisatawan_domestik' => 27,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-05-31',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 1,
                'wisatawan_domestik' => 107,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 23353000,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 2,
                'wisatawan_domestik' => 2694,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 3,
                'wisatawan_domestik' => 81,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 4,
                'wisatawan_domestik' => 139,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 5,
                'wisatawan_domestik' => 780,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 6,
                'wisatawan_domestik' => 31,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 7,
                'wisatawan_domestik' => 170,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 8115000,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 8,
                'wisatawan_domestik' => 783,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 574456147,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 9,
                'wisatawan_domestik' => 51,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 10,
                'wisatawan_domestik' => 24,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-06-30',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 1,
                'wisatawan_domestik' => 115,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 26037000,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 2,
                'wisatawan_domestik' => 3460,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 3,
                'wisatawan_domestik' => 76,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 4,
                'wisatawan_domestik' => 126,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 5,
                'wisatawan_domestik' => 882,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 6,
                'wisatawan_domestik' => 54,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 7,
                'wisatawan_domestik' => 175,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 8255000,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 8,
                'wisatawan_domestik' => 788,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 463776755,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 9,
                'wisatawan_domestik' => 43,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 10,
                'wisatawan_domestik' => 43,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-07-31',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 1,
                'wisatawan_domestik' => 111,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 24629000,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 2,
                'wisatawan_domestik' => 3182,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 3,
                'wisatawan_domestik' => 85,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 4,
                'wisatawan_domestik' => 112,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 5,
                'wisatawan_domestik' => 831,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 6,
                'wisatawan_domestik' => 51,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 7,
                'wisatawan_domestik' => 245,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 10940000,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 8,
                'wisatawan_domestik' => 856,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 567607584,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 9,
                'wisatawan_domestik' => 48,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 10,
                'wisatawan_domestik' => 54,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-08-31',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 1,
                'wisatawan_domestik' => 121,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 26543000,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 2,
                'wisatawan_domestik' => 3321,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 3,
                'wisatawan_domestik' => 65,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 4,
                'wisatawan_domestik' => 98,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 5,
                'wisatawan_domestik' => 773,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 6,
                'wisatawan_domestik' => 34,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 7,
                'wisatawan_domestik' => 204,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 10940000,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 8,
                'wisatawan_domestik' => 875,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 688210010,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 9,
                'wisatawan_domestik' => 77,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 10,
                'wisatawan_domestik' => 54,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-09-30',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 1,
                'wisatawan_domestik' => 118,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 28182000,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 2,
                'wisatawan_domestik' => 3636,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 3,
                'wisatawan_domestik' => 126,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 4,
                'wisatawan_domestik' => 105,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 5,
                'wisatawan_domestik' => 694,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 6,
                'wisatawan_domestik' => 57,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 7,
                'wisatawan_domestik' => 108,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 8,
                'wisatawan_domestik' => 1133,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 723076839,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 9,
                'wisatawan_domestik' => 68,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-10-31',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 1,
                'wisatawan_domestik' => 119,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 27791500,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 2,
                'wisatawan_domestik' => 3226,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 3,
                'wisatawan_domestik' => 103,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 4,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 5,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 6,
                'wisatawan_domestik' => 57,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 7,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 8,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 9,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-11-30',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 1,
                'wisatawan_domestik' => 111,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 2748000,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 2,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 3,
                'wisatawan_domestik' => 118,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 4,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 5,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 6,
                'wisatawan_domestik' => 67,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 7,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 8,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 9,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 10,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 11,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 12,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 13,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 14,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
            [
                'tanggal' => '2022-12-31',
                'id_hotel' => 15,
                'wisatawan_domestik' => 0,
                'wisatawan_mancanegara' => 0,
                'total_pendapatan' => 0,
            ],
        ];
        foreach ($rekap as $data) {
            Rekap::create($data);
        }
    }
}
